services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\Core\Ports\Rest\:
    resource: '../src/Core/Ports/Rest'
    tags: [ 'controller.service_arguments' ]

  command_handlers:
    resource: '../src/Core/Application/Command/*/*/*CommandHandler.php'
    namespace: App\Core\Application\Command\
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, bus: command.bus }

  query_handlers:
    namespace: App\Core\Application\Query\
    resource: '../src/Core/Application/Query/*/*/*QueryHandler.php'
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, bus: query.bus }

  event_handlers:
    namespace: App\Core\Application\
    resource: '../src/Core/Application/**/*EventHandler.php'
    autoconfigure: false
    tags:
      - { name: messenger.message_handler, bus: event.bus }

  infrastructure:
    namespace: App\Core\Infrastructure\
    resource: '../src/Core/Infrastructure/**/*.php'
    autoconfigure: false

  repositories:
    namespace: App\Core\Infrastructure\Repository\
    resource: '../src/Core/Infrastructure/Repository/*Repository.php'
    autoconfigure: false
    tags:
      - { name: doctrine.repository_service }

  symfony_commands:
    namespace: App\Core\Ports\Cli\
    resource: '../src/Core/Ports/Cli/*Command.php'
    autoconfigure: false
    tags:
      - { name: console.command }

  App\Core\Domain\Model\User\UserRepositoryInterface: '@App\Core\Infrastructure\Repository\UserRepository'

  App\Core\Domain\Model\Task\TaskRepositoryInterface: '@App\Core\Infrastructure\Repository\TaskRepository'

  App\Core\Domain\Model\User\UserFetcherInterface: '@App\Core\Infrastructure\Security\UserFetcher'

  App\Core\Domain\Model\User\UniqueUsernameSpecificationInterface: '@App\Core\Infrastructure\Specification\User\UniqueUsernameSpecification'