# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
        mapping:
            paths:
                - '%kernel.project_dir%/src/Core/Ports/Rest/SerializerMapping'
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
